### ISSUE TITLE
Crash: There was a severe problem during mod loading that has caused the game to fail

### ISSUE THREAD

**Issue by jensz12** [jensz12/Pixelmon#14]
[![YAMPST - Open source mod pack statistics tracker](http://files.yampst.net/static/banner-small.png)](https://yampst.net/)

Crash report collection powered by [YAMPST](https://yampst.net/).
### Environment data:

| Key | Value |
| --- | --- |
| Mod pack version | 3.1 |
| Minecraft version | 1.8.9 |
| Side | Client side |
### Comments by pack administrator:

_No comments._
### Full crash report:

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Java8CheckerCoremod (Pixelmon-1.8.9-4.2.3-universal.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 21.04.16 9:50
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.OutOfMemoryError: Java heap space
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:739)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:310)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:495)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOfRange(Unknown Source)
    at java.lang.String.<init>(Unknown Source)
    at java.lang.String.substring(Unknown Source)
    at java.lang.String.subSequence(Unknown Source)
    at java.util.regex.Pattern.split(Unknown Source)
    at java.util.regex.Pattern.split(Unknown Source)
    at com.pixelmonmod.pixelmon.client.models.smd.SmdAnimation.startParsingAnimation(SmdAnimation.java:90)
    at com.pixelmonmod.pixelmon.client.models.smd.SmdAnimation.loadSmdAnim(SmdAnimation.java:61)
    at com.pixelmonmod.pixelmon.client.models.smd.SmdAnimation.<init>(SmdAnimation.java:29)
    at com.pixelmonmod.pixelmon.client.models.smd.ValveStudioModel.loadQC(ValveStudioModel.java:91)
    at com.pixelmonmod.pixelmon.client.models.smd.ValveStudioModel.<init>(ValveStudioModel.java:54)
    at com.pixelmonmod.pixelmon.client.models.smd.ValveStudioModelLoader.loadModel(ValveStudioModelLoader.java:70)
    at com.pixelmonmod.pixelmon.enums.EnumCustomModel.preloadModels(EnumCustomModel.java:285)
    at com.pixelmonmod.pixelmon.client.ClientProxy.registerRenderers(ClientProxy.java:210)
    at com.pixelmonmod.pixelmon.Pixelmon.init(Pixelmon.java:130)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (x86) version 10.0
    Java Version: 1.8.0_77, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode, sharing), Oracle Corporation
    Memory: 1363880 bytes (1 MB) / 518979584 bytes (494 MB) up to 518979584 bytes (494 MB)
    JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:MaxPermSize=128m -Xmx1024M -Xms256M -Xmx512M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.19 Powered by Forge 11.15.1.1722 9 mods loaded, 9 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHI    mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHI    FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1722.jar) 
    UCHI    Forge{11.15.1.1722} [Minecraft Forge] (forge-1.8.9-11.15.1.1722.jar) 
    UCHI    CustomMainMenu{2.0} [Custom Main Menu] (CustomMainMenu-MC1.8.9-2.0.jar) 
    UCHE    pixelmon{4.2.3} [Pixelmon] (Pixelmon-1.8.9-4.2.3-universal.jar) 
    UCHE    itemfinder{2.1.0} [ItemFinder] (ItemFinder-1.8.9-2.1.0-universal.jar) 
    UCHE    pixelextras{2.1.1} [Pixel Extras] (PixelExtras-1.8.9-2.1.1-universal.jar) 
    UCHE    pixelmonfriends{1.0} [Pixelmon Friends] (pixelmonfriends-1.8.9-1.3.0-universal.jar) 
    UCHI    yampst{1.3.6} [YAMPST] (Yampst-Matrieuxelmon-3.1.jar) 
    Loaded coremods (and transformers): 
Java8CheckerCoremod (Pixelmon-1.8.9-4.2.3-universal.jar)

    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 358.91' Renderer: 'GeForce GTX 960/PCIe/SSE2'
```

**Comment by jensz12** [comment]
java.lang.OutOfMemoryError!
